# Generated by Django 5.2.4 on 2025-07-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('professeur', 'Professeur')], default='admin', max_length=20),
        ),
    ]
