# Generated by Django 5.2.4 on 2025-07-29 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='professeurs',
            field=models.ManyToManyField(blank=True, related_name='dossiers_attribues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueaction',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='historiqueaction',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='rapportanalyse',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapportanalyse',
            name='dossier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='dossiers.dossier'),
        ),
    ]
