# Generated by Django 5.2.4 on 2025-07-29 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poids', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_arrivee', models.DateField()),
                ('pays_origine', models.CharField(max_length=100)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='dossiers.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.IntegerField()),
                ('decision', models.CharField(choices=[('equivalence_complete', 'Équivalence complète'), ('equivalence_conditions', 'Équivalence sous conditions'), ('refus', 'Refus')], max_length=30)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('recommandations', models.TextField()),
                ('commentaires', models.TextField(blank=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='dossiers.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('universite', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='dossiers.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaires', models.TextField(blank=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dossiers.candidat')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.competence')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('affectation', 'Affectation de dossier'), ('traitement', 'Traitement terminé'), ('evaluation', 'Nouvelle évaluation'), ('system', 'Notification système')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dossiers.dossier')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PieceManquante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_manquantes', to='dossiers.candidat')),
            ],
        ),
    ]
