# Generated by Django 5.2.4 on 2025-07-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_competence_candidat_decisioncommission_diplome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcompetence',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
