# Generated by Django 5.2.4 on 2025-07-30 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_alter_evaluationcompetence_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('A', 'Phase A - Vérification des documents'), ('B', 'Phase B - Analyse des diplômes'), ('C', 'Phase C - Évaluation des compétences'), ('D', 'Phase D - Comparaison des programmes'), ('E', 'Phase E - Décision finale')], max_length=1)),
                ('ordre', models.IntegerField()),
                ('description', models.TextField()),
                ('est_obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('diplome', 'Diplôme'), ('releve', 'Relevé de notes'), ('programme', 'Programme des cours'), ('traduction', 'Traduction certifiée'), ('attestation', 'Attestation'), ('autre', 'Autre')], max_length=20)),
                ('nom_document', models.CharField(max_length=255)),
                ('est_present', models.BooleanField(default=False)),
                ('est_valide', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_verifies', to='dossiers.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('probleme', 'Problème détecté')], default='en_attente', max_length=20)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_etapes', to='dossiers.candidat')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.etapeevaluation')),
            ],
            options={
                'unique_together': {('candidat', 'etape')},
            },
        ),
    ]
