# Generated by Django 5.2.4 on 2025-07-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_etapeevaluation_documentverification_evaluationetape'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_diplome', models.CharField(max_length=255, verbose_name='Titre du diplôme')),
                ('description_titre', models.TextField(blank=True, verbose_name='Description du titre')),
                ('date_obtention', models.DateField(verbose_name="Date d'obtention du diplôme")),
                ('description_date', models.TextField(blank=True, verbose_name='Description de la date')),
                ('pays_diplome', models.CharField(max_length=100, verbose_name='Pays du diplôme')),
                ('description_pays', models.TextField(blank=True, verbose_name='Description du pays')),
                ('universite_ecole', models.CharField(max_length=255, verbose_name='Université ou École')),
                ('description_etablissement', models.TextField(blank=True, verbose_name="Description de l'établissement")),
                ('specialite', models.CharField(blank=True, max_length=255, verbose_name='Spécialité éventuelle')),
                ('description_specialite', models.TextField(blank=True, verbose_name='Description de la spécialité')),
                ('duree_formation', models.CharField(max_length=100, verbose_name='Durée de la formation')),
                ('description_duree', models.TextField(blank=True, verbose_name='Description de la durée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs_diplome', to='dossiers.candidat')),
            ],
            options={
                'verbose_name': 'Indicateur de diplôme',
                'verbose_name_plural': 'Indicateurs de diplômes',
            },
        ),
    ]
