# Generated by Django 5.2.4 on 2025-07-30 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_indicateurdiplome'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_nouveau_dossier', models.BooleanField(help_text="Indique si c'est un nouveau dossier (Oui) ou un dossier déjà traité (Non)", verbose_name='Nouveau dossier')),
                ('a_decision_anterieure', models.BooleanField(default=False, verbose_name='A une décision antérieure')),
                ('date_decision_anterieure', models.DateField(blank=True, null=True, verbose_name='Date de la décision antérieure')),
                ('decision_anterieure', models.TextField(blank=True, verbose_name='Détails de la décision antérieure')),
                ('pieces_demandees', models.TextField(blank=True, verbose_name='Pièces complémentaires demandées')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_dossier', to='dossiers.candidat')),
            ],
            options={
                'verbose_name': 'État du dossier',
                'verbose_name_plural': 'États des dossiers',
            },
        ),
    ]
