# Generated by Django 5.2.4 on 2025-07-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_etatdossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistanceAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciences_geodesiques_contenus', models.TextField(blank=True, verbose_name='Contenus suivis en Sciences géodésiques')),
                ('sciences_geodesiques_commentaires', models.TextField(blank=True, verbose_name='Commentaires Sciences géodésiques')),
                ('sciences_geodesiques_note', models.IntegerField(blank=True, null=True, verbose_name='Note Sciences géodésiques (0-16)')),
                ('topographie_contenus', models.TextField(blank=True, verbose_name='Contenus suivis en Topographie')),
                ('topographie_commentaires', models.TextField(blank=True, verbose_name='Commentaires Topographie')),
                ('topographie_note', models.IntegerField(blank=True, null=True, verbose_name='Note Topographie (0-16)')),
                ('photogrammetrie_contenus', models.TextField(blank=True, verbose_name='Contenus suivis en Photogrammétrie')),
                ('photogrammetrie_commentaires', models.TextField(blank=True, verbose_name='Commentaires Photogrammétrie')),
                ('photogrammetrie_note', models.IntegerField(blank=True, null=True, verbose_name='Note Photogrammétrie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consistance_academique', to='dossiers.candidat')),
            ],
            options={
                'verbose_name': 'Consistance académique',
                'verbose_name_plural': 'Consistances académiques',
            },
        ),
    ]
