# Generated by Django 5.2.4 on 2025-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_consistanceacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_commentaires',
            field=models.TextField(blank=True, verbose_name='Commentaires Cartographie'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_contenus',
            field=models.TextField(blank=True, verbose_name='Contenus suivis en Cartographie'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_drone',
            field=models.BooleanField(default=False, verbose_name='Drone (Cartographie)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Cartographie (0-16)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_commentaires',
            field=models.TextField(blank=True, verbose_name='Commentaires Droit foncier'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_contenus',
            field=models.TextField(blank=True, verbose_name='Contenus suivis en Droit foncier'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Droit foncier (0-16)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_commentaires',
            field=models.TextField(blank=True, verbose_name='Commentaires SIG'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_contenus',
            field=models.TextField(blank=True, verbose_name='Contenus suivis en SIG'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note SIG (0-10)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stage_cadastre',
            field=models.BooleanField(default=False, verbose_name='Stage cadastre ANCFCC (2 semaines)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stage_conservation_fonciere',
            field=models.BooleanField(default=False, verbose_name='Stage conservation foncière ANCFCC (1 semaine)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stage_geodesie',
            field=models.BooleanField(default=False, verbose_name='Stage de Géodésie (2 semaines)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stage_photogrammetrie',
            field=models.BooleanField(default=False, verbose_name='Stage de Photogrammétrie (2 semaines)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stage_topographie',
            field=models.BooleanField(default=False, verbose_name='Stage de Topographie (2 semaines)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='teledetection_commentaires',
            field=models.TextField(blank=True, verbose_name='Commentaires Télédétection'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='teledetection_contenus',
            field=models.TextField(blank=True, verbose_name='Contenus suivis en Télédétection'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='teledetection_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Télédétection (0-10)'),
        ),
    ]
