# Generated by Django 5.2.4 on 2025-07-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_consistanceacademique_cartographie_commentaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_commentaires',
            field=models.TextField(blank=True, verbose_name='Commentaires sur les stages'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_contenus',
            field=models.TextField(blank=True, verbose_name='Contenus des stages effectués'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Stages (0-10)'),
        ),
    ]
