# Generated by Django 5.2.4 on 2025-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_consistanceacademique_stages_commentaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_dao_cao',
            field=models.BooleanField(default=False, verbose_name='DAO/CAO'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_representation_cartographique',
            field=models.BooleanField(default=False, verbose_name='Systèmes de représentation cartographique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_semiologie_langage',
            field=models.BooleanField(default=False, verbose_name='Sémiologie et langage cartographique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_thematique',
            field=models.BooleanField(default=False, verbose_name='Cartographie thématique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='cartographie_topographique',
            field=models.BooleanField(default=False, verbose_name='Cartographie topographique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_droit',
            field=models.BooleanField(default=False, verbose_name='Droit foncier'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_gestion_amenagement',
            field=models.BooleanField(default=False, verbose_name='Gestion foncière et aménagement'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_reglementations',
            field=models.BooleanField(default=False, verbose_name='Réglementations cadastre et propriété'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='droit_foncier_techniques_cadastrales',
            field=models.BooleanField(default=False, verbose_name='Techniques cadastrales'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='photogrammetrie_base_approfondie',
            field=models.BooleanField(default=False, verbose_name='Base et approfondie'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_ajustements_compensations',
            field=models.BooleanField(default=False, verbose_name='Ajustements et compensations'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_astronomie_geodesie_spatiale',
            field=models.BooleanField(default=False, verbose_name='Astronomie et géodésie spatiale'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_geodesie_appliquee',
            field=models.BooleanField(default=False, verbose_name='Géodésie appliquée'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_geodesie_geometrique',
            field=models.BooleanField(default=False, verbose_name='Géodésie géométrique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_geodesie_physique',
            field=models.BooleanField(default=False, verbose_name='Géodésie physique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_gnss',
            field=models.BooleanField(default=False, verbose_name='GNSS'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_micro_geodesie',
            field=models.BooleanField(default=False, verbose_name='Micro-géodésie'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_projections_cartographiques',
            field=models.BooleanField(default=False, verbose_name='Projections cartographiques'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sciences_systemes_referentiels',
            field=models.BooleanField(default=False, verbose_name='Systèmes et référentiels géodésiques'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_bases',
            field=models.BooleanField(default=False, verbose_name='Bases en SIG'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_bases_donnees_geographiques',
            field=models.BooleanField(default=False, verbose_name='Bases de données géographiques'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_gestion_analyse_donnees',
            field=models.BooleanField(default=False, verbose_name='Gestion et analyse des données spatiales'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='sig_web_mapping',
            field=models.BooleanField(default=False, verbose_name='Web mapping'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='teledetection_applications',
            field=models.BooleanField(default=False, verbose_name='Applications de la télédétection'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='teledetection_bases_physiques',
            field=models.BooleanField(default=False, verbose_name='Bases physiques de la télédétection'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='teledetection_traitement_images',
            field=models.BooleanField(default=False, verbose_name="Traitement d'images optique/radar"),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='topographie_techniques_mensuration',
            field=models.BooleanField(default=False, verbose_name='Techniques de mensuration'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='topographie_theorique_pratique',
            field=models.BooleanField(default=False, verbose_name='Théorique et pratique'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='topographie_topometrique_instrumentation',
            field=models.BooleanField(default=False, verbose_name='Topométrique et instrumentation'),
        ),
    ]
