# Generated by Django 5.2.4 on 2025-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0011_consistanceacademique_cartographie_dao_cao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='photogrammetrie_aerotriangulation',
            field=models.BooleanField(default=False, verbose_name='Aérotriangulation'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='photogrammetrie_drone',
            field=models.BooleanField(default=False, verbose_name='Drone'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='photogrammetrie_photographies_aeriennes',
            field=models.BooleanField(default=False, verbose_name='Mise en place des photographies aériennes'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='photogrammetrie_produits_derives',
            field=models.BooleanField(default=False, verbose_name='Génération de produits dérivés (MNT/Ortho)'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='photogrammetrie_restitution',
            field=models.BooleanField(default=False, verbose_name='Restitution photogrammétrique'),
        ),
    ]
