# Generated by Django 5.2.4 on 2025-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0012_consistanceacademique_photogrammetrie_aerotriangulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='criteres_personnalises',
            field=models.JSONField(blank=True, default=list, verbose_name='Critères personnalisés'),
        ),
    ]
