# Generated by Django 5.2.4 on 2025-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0013_consistanceacademique_criteres_personnalises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistanceacademique',
            name='photogrammetrie_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Photogrammétrie (0-20)'),
        ),
    ]
