# Generated by Django 5.2.4 on 2025-07-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0014_alter_consistanceacademique_photogrammetrie_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etatdossier',
            options={'verbose_name': "Grille d'évaluation des dossiers", 'verbose_name_plural': "Grilles d'évaluation des dossiers"},
        ),
    ]
