# Generated by Django 5.2.4 on 2025-07-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0015_alter_etatdossier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportanalyse',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre du rapport'),
        ),
        migrations.AddField(
            model_name='rapportanalyse',
            name='type_rapport',
            field=models.CharField(choices=[('analyse_preliminaire', 'Analyse préliminaire'), ('evaluation_detaille', 'Évaluation détaillée'), ('recommandation', 'Recommandation'), ('decision_finale', 'Décision finale'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Type de rapport'),
        ),
        migrations.AlterField(
            model_name='rapportanalyse',
            name='contenu',
            field=models.TextField(verbose_name='Contenu du rapport'),
        ),
        migrations.AlterField(
            model_name='rapportanalyse',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Document joint'),
        ),
    ]
