# Generated by Django 5.2.4 on 2025-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0016_rapportanalyse_titre_rapportanalyse_type_rapport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportanalyse',
            name='titre',
            field=models.CharField(default="Rapport d'analyse", max_length=255, verbose_name='Titre du rapport'),
        ),
    ]
