# Generated by Django 5.2.4 on 2025-07-30 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0017_alter_rapportanalyse_titre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistanceacademique',
            name='photogrammetrie_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Photogrammétrie (0-16)'),
        ),
        migrations.CreateModel(
            name='DossierTraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('demandeur_candidat', models.CharField(max_length=200, verbose_name='Demandeur/Candidat')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence')),
                ('date_envoi', models.DateField(verbose_name="Date d'envoi")),
                ('reference_reception', models.CharField(blank=True, max_length=100, verbose_name='Référence de réception')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('diplome', models.CharField(max_length=200, verbose_name='Diplôme')),
                ('universite', models.CharField(max_length=200, verbose_name='Université')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('date_avis', models.DateField(blank=True, null=True, verbose_name="Date de l'avis")),
                ('avis_commission', models.TextField(verbose_name='Avis de la commission')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('reunions', models.JSONField(blank=True, default=list, verbose_name='Réunions')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Dossier traité',
                'verbose_name_plural': 'Dossiers traités',
                'ordering': ['-date_creation'],
            },
        ),
    ]
