# Generated by Django 5.2.4 on 2025-07-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0018_alter_consistanceacademique_photogrammetrie_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistanceacademique',
            name='droit_foncier_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Droit foncier (0-10)'),
        ),
    ]
