# Generated by Django 5.2.4 on 2025-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0020_dossiertraite_pays_autre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureEvaluationGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciences_geodesiques_note_max', models.IntegerField(default=16, verbose_name='Note max Sciences géodésiques')),
                ('topographie_note_max', models.IntegerField(default=16, verbose_name='Note max Topographie')),
                ('photogrammetrie_note_max', models.IntegerField(default=16, verbose_name='Note max Photogrammétrie')),
                ('cartographie_note_max', models.IntegerField(default=16, verbose_name='Note max Cartographie')),
                ('droit_foncier_note_max', models.IntegerField(default=10, verbose_name='Note max Droit foncier')),
                ('sig_note_max', models.IntegerField(default=10, verbose_name='Note max SIG')),
                ('teledetection_note_max', models.IntegerField(default=10, verbose_name='Note max Télédétection')),
                ('stages_note_max', models.IntegerField(default=10, verbose_name='Note max Stages')),
                ('criteres_personnalises_globaux', models.JSONField(blank=True, default=list, verbose_name='Critères personnalisés globaux')),
                ('competences_par_critere', models.JSONField(blank=True, default=dict, verbose_name='Compétences par critère')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Structure active')),
            ],
            options={
                'verbose_name': "Structure d'évaluation globale",
                'verbose_name_plural': "Structures d'évaluation globales",
            },
        ),
    ]
