# Generated by Django 5.2.4 on 2025-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0021_structureevaluationglobale'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureevaluationglobale',
            name='competences_criteres_fixes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Compétences des critères fixes'),
        ),
        migrations.AddField(
            model_name='structureevaluationglobale',
            name='criteres_fixes_supprimes',
            field=models.JSONField(blank=True, default=list, verbose_name='Critères fixes supprimés'),
        ),
    ]
