# Generated by Django 5.2.4 on 2025-08-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0022_structureevaluationglobale_competences_criteres_fixes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_configurables',
            field=models.JSONField(blank=True, default=list, verbose_name='Stages configurables'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_configurables_cochees',
            field=models.JSONField(blank=True, default=list, verbose_name='Stages configurables cochés'),
        ),
        migrations.AddField(
            model_name='structureevaluationglobale',
            name='stages_configurables',
            field=models.JSONField(blank=True, default=list, verbose_name='Stages configurables'),
        ),
    ]
