# Generated by Django 5.2.4 on 2025-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0023_consistanceacademique_stages_configurables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureevaluationglobale',
            name='stages_defaut_supprimes',
            field=models.JSONField(blank=True, default=list, verbose_name='Stages par défaut supprimés'),
        ),
    ]
