# Generated by Django 5.2.4 on 2025-08-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0024_structureevaluationglobale_stages_defaut_supprimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistanceacademique',
            name='message_stages_non_acheves',
            field=models.TextField(blank=True, verbose_name='Message pour stages non achevés'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_acheves',
            field=models.BooleanField(default=False, verbose_name='Stages achevés'),
        ),
        migrations.AddField(
            model_name='consistanceacademique',
            name='stages_non_acheves',
            field=models.BooleanField(default=False, verbose_name='Stages non achevés'),
        ),
    ]
