# Generated by Django 5.2.4 on 2025-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0025_consistanceacademique_message_stages_non_acheves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisioncommission',
            name='decision',
            field=models.CharField(choices=[('equivalence_accorder', 'Équivalence accordée'), ('completement_dossier', 'Complètement de dossier'), ('invitation_soutenance', 'Invitation soutenance'), ('invitation_concours', 'Invitation concours'), ('non_equivalent', 'Non équivalent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('affectation', 'Affectation de dossier'), ('traitement', 'Traitement terminé'), ('evaluation', 'Nouvelle évaluation'), ('system', 'Notification système'), ('retour', "Retour à l'admin"), ('renvoi', 'Renvoyer au professeur')], max_length=20),
        ),
    ]
